### ISSUE TITLE
Script is not running well

### ISSUE THREAD

**Issue by galhalperin1** [agallego-css/tools#1]
i try to run the script via powershell and powershell v7 and it not working please fix it :-)

**Comment by DrummerViking** [comment]
which one of the tool is not working?

**Comment by galhalperin1** [comment]
Manage folder premission gui

בתאריך יום ב׳, 26 ביולי 2021, 15:50, מאת Agustin Gallegos [MSFT] ‏<
***@***.***>:

**Comment by DrummerViking** [comment]
Done. it is working for me now on PS 5.1
it is expected to fail in PS7.

please retry and let me know

**Comment by galhalperin1** [comment]
how did you run it i try with right click and run with powershell

‫בתאריך יום ג׳, 27 ביולי 2021 ב-16:31 מאת ‪Agustin Gallegos [MSFT]‬‏ <‪
***@***.***‬‏>:‬

**Comment by DrummerViking** [comment]
download the PS1 from https://raw.githubusercontent.com/agallego-css/tools/master/Manage-FolderPermissions-gui/Manage-FolderPermissionsGUI.ps1
and execute from Windows Powershell:
``` powershell
PS C:\> .\Manage-FolderPermissionsGUI.ps1
```

**Comment by galhalperin1** [comment]
[image: image.png]

‫בתאריך יום ג׳, 27 ביולי 2021 ב-20:28 מאת ‪Agustin Gallegos [MSFT]‬‏ <‪
***@***.***‬‏>:‬

**Comment by DrummerViking** [comment]
can't see the image.

**Comment by galhalperin1** [comment]
[image: image.png]


‫בתאריך יום ד׳, 28 ביולי 2021 ב-14:09 מאת ‪Agustin Gallegos [MSFT]‬‏ <‪
***@***.***‬‏>:‬

**Comment by DrummerViking** [comment]
still not seeing the image attach.
please describe the error you have.

**Comment by galhalperin1** [comment]
https://www8.zippyshare.com/v/xCOcH2Ew/file.html


‫בתאריך יום ד׳, 28 ביולי 2021 ב-17:15 מאת ‪Agustin Gallegos [MSFT]‬‏ <‪
***@***.***‬‏>:‬

**Comment by DrummerViking** [comment]
you are downloading the file incorrectly.
access the raw content here: https://raw.githubusercontent.com/agallego-css/tools/master/Manage-FolderPermissions-gui/Manage-FolderPermissionsGUI.ps1
copy and save the text in a new notepad file, later save it as .ps1.

then it should run just fine.

**Comment by galhalperin1** [comment]
Thanks I just make right click on the github file and save the url and download the powershell ps1 file

I will try it

Maybe you have more great tools that I could use ?

**Comment by DrummerViking** [comment]
feel free to check my repositories. all my public tools are there.

**Comment by galhalperin1** [comment]
dear agustin there is an option for you to make script for gui interface
for delegation ?
it will be very helpful :-)
[image: image.png]

https://github.com/MicrosoftDocs/office-docs-powershell/issues/6327



‫בתאריך יום ו׳, 30 ביולי 2021 ב-20:22 מאת ‪Agustin Gallegos [MSFT]‬‏ <‪
***@***.***‬‏>:‬
