### ISSUE TITLE
Insert Microsoft365 Groups in tool: Delete Meetings using a GUI

### ISSUE THREAD

**Issue by johnnynezzi** [agallego-css/tools#2]
Hi Agustin,

First of all congratulations for the tool, it is very well built.

My issue is with Microsoft365 group meetings, can't find the same through the tool..

Return

`Exception when calling "Bind" with "2" argument(s): "The SMTP address has no mailbox associated with it."
No C:\Users\Administrador\Desktop\DeleteMeetings-GUI.ps1:308 caractere:13
            $Calendarfolder = [Microsoft.Exchange.WebServices.Data.Fo ...
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
     FullyQualifiedErrorId : ServiceResponseException

Cannot call a method on a null-valued expression.
No C:\Users\Administrador\Desktop\DeleteMeetings-GUI.ps1:316 caractere:13
             $Appointments = $Calendarfolder.FindAppointments($calView ...
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     FullyQualifiedErrorId : InvokeMethodOnNull`

**Comment by DrummerViking** [comment]
Hello Johnny.

I'm glad that you liked the tool.
That's a good catch, I haven't thought about M365 Groups (honestly, I haven't checked with shared mailbox neither).

if this is urgent, you can try to investigate yourself, and submit your suggestions to the code.
I will be busy for a few days, so I won't be able to check on this right now.

**Comment by DrummerViking** [comment]
I have checked and have not found a way to connect to unifiedGroups using EWS.
I will be closing this issue as it is. if you later find a way to do it, feel free to push your suggestion in a pull request, or let me know and I can take a look.

**Comment by johnnynezzi** [comment]
Alright Agustin, I also tried to reach the groups and improve their application, but I was not successful. Anyway, thanks for your attention!
