### ISSUE TITLE
Too many items??

### ISSUE THREAD

**Issue by lmarianko** [agallego-css/tools#3]
Getting this error when trying to run the script on a user - 
![exportcalnew](https://user-images.githubusercontent.com/52173994/174851156-b8b684ac-6c73-442d-9d09-0bd9d045fbda.png)

**Comment by DrummerViking** [comment]
I have updated the Export-MeetingsItems script, increasing the folder view from 10k to 1M items. 
please retry and let me know if it keeps failing.
